apiVersion: gateway.k8s.aws/v1
kind: LoadBalancerConfiguration
metadata:
  name: roboshop-alb
  namespace: roboshop
spec:
  scheme: internet-facing
  ipAddressType: ipv4
  listenerConfigurations:
  - protocolPort: HTTPS:443
    certificates:
    - arn:aws:acm:us-east-1:121973526213:certificate/c9b24846-7304-4f7b-b921-89ee5fce9833
# We are going to use ALB, Listener